version: '3'

services:
  db-camera:
    image: mariadb:10.3
    container_name: db-camera
    volumes:
      - container-volume:/var/lib/mysql
      - ./camera.sql:/docker-entrypoint-initdb.d/camera.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: camera
    restart: always

  phpmyadmin-camera:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-camera
    links:
      - db-camera
    ports:
      - "9000:80"
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: db-camera:3306
    restart: always

  camera-service:
    build: .
    container_name: camera-service
    depends_on:
      - db-camera
    links:
      - db-camera
#    ports:
#      - "50052:50052"
    environment:
      DB_HOST: "db-camera"
      DB_PORT: "3306"
      DB_NAME: "camera"
      DB_ROOT_PASS: "root"
    restart: always

volumes:
  container-volume: